#ifndef DEFINE_H
#define DEFINE_H

#define MAX_PACKET_SIZE 65536

#define MAC_ADDRESS_SIZE 6
#define IP_ADDRESS_SIZE 4

#define TPID 0x8100
#define ARP_ETHERTYPE 0x0806

#define IPV4_ETHERTYPE 0x0800
#define MAX_OPTIONS_SIZE 40

#define IPV6_ETHERTYPE 0x86dd
#define ADDRESS_SIZE 16

#define ICMP_PROTOCOL 0x01

#define ICMPV6_PROTOCOL 58

#define TCP_PROTOCOL 0x06
#define RESERVED_BITS 3

#define UDP_PROTOCOL 17

#define HTTP_PORT 80
#define MAX_HTTP_HEADERS 50
#define HTTP_METHOD_SIZE 16
#define HTTP_URI_SIZE 1024
#define HTTP_VERSION_SIZE 16
#define HTTP_STATUS_TEXT_SIZE 128
#define HTTP_HEADER_NAME_SIZE 128
#define HTTP_HEADER_VALUE_SIZE 1024

#define HTTPS_PORT 443
#define MAX_TLS_FRAGMENT_SIZE 16384

#define DNS_PORT 53
#define DNS_FLAGS 16
#define DNS_NAME_SIZE 256
#define MAX_DNS_QUESTIONS 10
#define MAX_DNS_RECORDS 50
#define MAX_DNS_RDATA_SIZE 1024

#define SERVER_DHCP_PORT 67
#define CLIENT_DHCP_PORT 68
#define MAX_DHCP_OPTIONS 64
#define DHCP_OPTION_DATA_SIZE 255

#define CONTROL_FTP_PORT 21
#define ACTIVE_FTP_PORT 20
#define FTP_COMMAND_SIZE 16
#define FTP_ARGUMENT_SIZE 1024
#define FTP_STATUS_TEXT_SIZE 1024

#define SSH_PORT 22
#define SSH_IDENTIFICATION_SIZE 256
#define MAX_SSH_PAYLOAD_SIZE 35000

#define NTP_PORT 123

#define TELNET_PORT 23
#define MAX_TELNET_DATA_SIZE 1024
#define MAX_TELNET_COMMANDS 64
#define TELNET_IAC 0xFF
#define TELNET_SE 0xF0
#define TELNET_NOP 0xF1
#define TELNET_DM 0xF2
#define TELNET_BRK 0xF3
#define TELNET_IP 0xF4
#define TELNET_AO 0xF5
#define TELNET_AYT 0xF6
#define TELNET_EC 0xF7
#define TELNET_EL 0xF8
#define TELNET_GA 0xF9
#define TELNET_SB 0xFA
#define TELNET_WILL 0xFB
#define TELNET_WONT 0xFC
#define TELNET_DO 0xFD
#define TELNET_DONT 0xFE

#define PRINT_LABEL_WIDTH 24
#define SUB_LABEL_WIDTH 4

#endif