#ifndef DEFINE_H
#define DEFINE_H

#define MAX_PACKET_SIZE 65536

#define MAC_ADDRESS_SIZE 6
#define IP_ADDRESS_SIZE 4

#define TPID 0x8100
#define ARP_ETHERTYPE 0x0806

#define IPV4_ETHERTYPE 0x0800
#define MAX_OPTIONS_SIZE 40

#define IPV6_ETHERTYPE 0x86dd
#define ADDRESS_SIZE 16

#define ICMP_PROTOCOL 0x01

#define ICMPV6_PROTOCOL 58

#define TCP_PROTOCOL 0x06
#define RESERVED_BITS 3

#define UDP_PROTOCOL 17

#define HTTP_PORT 80

#define HTTPS_PORT 443

#define DNS_PORT 53

#define SERVER_DHCP_PORT 67
#define CLIENT_DHCP_PORT 68

#define CONTROL_FTP_PORT 21
#define ACTIVE_FTP_PORT 20

#define SSH_PORT 22

#define NTP_PORT 123

#define TELNET_PORT 23

#endif